#!/usr/bin/env php
<?php

use Monolog\Handler\RotatingFileHandler;
use Symfony\Component\Console\Application;

const ROOT = __DIR__;
require ROOT .'/vendor/autoload.php';

$dot = \Dotenv\Dotenv::createImmutable(ROOT );
$dot->load();

$level = isset($_ENV['debug']) ? \Monolog\Logger::DEBUG : \Monolog\Logger::WARNING;
$_ENV['LOG_LEVEL'] = $level;

$logger = new \Monolog\Logger('cli', [
    new RotatingFileHandler(ROOT . '/log/telegram.log',5, $level)
]);

$app = new Application();
foreach (scandir(__DIR__ . '/lib/cli/') as $fileName){
    if(str_ends_with($fileName, '.php')){
        $class = '\\cli\\' . substr($fileName, 0, -4);
        $app->add(new $class); // remove .php from filename
    }
}

$app->run();